### ISSUE TITLE
 Variable confusion causes errors while creating new project

### ISSUE THREAD

**Issue by timze216** [HaoKeLab/ensembleCNV#5]
In `ensembleCNV/create_new_project.sh` line 27:  
`mkdir -p ${WKDIR}/01_initial_call/run_QuantiSNP/results/res` should be `mkdir -p ${wkdir}/01_initial_call/run_QuantiSNP/results/res` ?

Otherwise it will actually create `/01_initial_call` at  root directory

**Comment by zhongyangzhang** [comment]
Many thanks for pointing out this error. It has been corrected.
